services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 9000:9000
    environment:
      - VUE_APP_API_URL=http://localhost:3000/
    depends_on:
      - backend
    restart: always
  backend:
    container_name: backend
    image: backend
    build:
      context: ./api
      dockerfile: backend.dockerfile
    ports:
      - 3000:3000
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5431:5431
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
